name: CI

on:
  push:
    branches:
      - master

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build
          cd dist/
      - uses: primer/publish@master
        env:
          GITHUB_TOKEN: $GITHUB_TOKEN
          NPM_AUTH_TOKEN: $NPM_TOKEN
