name: CI

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build
          cat ./dist/package.json
      - uses: primer/publish@v2.0.0
        with:
          args: "--dir=dist"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
